version: '3.9'

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: images/Dockerfile
    restart: always
    env_file:
      - app/src/.env
    ports:
      - "5000:5000"
#    depends_on:
#      - postgres
    volumes:
      - app-data:/app
    entrypoint: ["gunicorn", "-w", "4", "--bind", "0.0.0.0:5000", "manage:application"]

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: images/Dockerfile
    restart: always
    env_file:
      - api/src/.env
    ports:
      - "5001:5001"
    #    depends_on:
    #      - postgres
    volumes:
      - api-data:/api
    entrypoint: [ "gunicorn", "-w", "4", "--bind", "0.0.0.0:5001", "manage:application" ]

#  postgres:
#    container_name: postgres
#    image: postgres:14.4-alpine
#    restart: always
#    environment:
#      - POSTGRES_DB=fuel_prices
#      - POSTGRES_USER=fuel_prices
#      - POSTGRES_PASSWORD=fuel_prices
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data/

volumes:
  app-data:
    name: app-data
  api-data:
    name: api-data
#  postgres-data:
#    name: postgres-data