version: '3.9'

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: images/Dockerfile
    restart: always
    env_file:
      - app/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    volumes:
      - app-data:/app
      - static-volume:/app/src/static/

  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    restart: always
    env_file:
      - app/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    container_name: redis
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - "6379:6379"

  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    env_file:
      - app/.env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - nginx-data:/var/log/nginx
      - static-volume:/app/src/static/
      - /certbot/www:/var/www/certbot/:ro
      - /certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes:
      - /certbot/www/:/var/www/certbot/:rw
      - /certbot/conf/:/etc/letsencrypt/:rw


volumes:
  app-data:
    name: app-data
  static-volume:
    name: static-files
  postgres-data:
    name: postgres-data
  nginx-data:
    name: nginx-data