name: tox CI

on:
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    working-directory: ./app

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.9' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python for ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Installing Dependencies
        run: pip install tox tox-gh-actions

      - name: Running tests with Tox
        run: tox
